# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks deleted

# Setup
title:            Jillian Brown
tagline:          'NLP Engineer'
description:      'NLP engineer and linguistic. From South Carolina, USA, currently based in Nancy, France.'
url:              jillianjrb.github.io
baseurl:          ""

author:
  name:           'Jillian Brown'
  url:            https://www.linkedin.com/in/jillian-brown-372585264/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
