# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Jillian Brown
tagline:          'MSc in NLP'
description:      'NLP engineer and linguist. From South Carolina, USA, currently based in Nancy, France.'
url:              "https://jillianjrb.github.io"
baseurl:          ""

author:
  name:           'Jillian Brown'
  url:            "https://www.linkedin.com/in/jillian-brown-372585264/"

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-paginate
  
# Custom vars
version:          1.0

github:
  repo:           "https://github.com/poole/hyde"
